version: "3.8"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - 4200:4200
      - 49153:49153

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=test_db
    links:
      - db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    links:
      - db

  db:
    image: postgres:11.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
