version: "3.8"

services:
  frontend:
    build: frontend
    ports:
      - "80:80"

  backend:
    build: backend
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=test_db
    links:
      - db

  db:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
